#ifndef DEFINE_H
#define DEFINE_H

constexpr uint16_t DELAY_1S = 1000;
constexpr uint16_t DELAY_2S = 2000;
constexpr uint16_t DELAY_3S = 3000;
constexpr uint16_t DELAY_5S = 5000;

namespace utils
{
    enum class CONTROL_MODE : uint8_t
    {
        NONE = 0U,
        DISPLAY_ALL,
        CONNECT_WIFI,
        CONNECT_WIFI_DONE,
        CONNECT_WIFI_FAILED,
        CONNEC_WIFI_FAILED_SSID_PASSWORD_EMPTY,
        CONNECT_FIREBASE,
        CONNECT_FIREBASE_DONE,
        CONNECT_FIREBASE_FAILED,
        CONNECT_FIREBASE_GET_TOKEN,
        CONNECT_NTP,
        CONNECT_NTP_DONE,
        CONNECT_NTP_FAILED,
        SETTING_BUTTON_IR_REMOTE_START,
        SETTING_BUTTON_IR_REMOTE,
        SETTING_BUTTON_IR_REMOTE_DONE,
        SETTING_RTC_TIME_START,
        SETTING_RTC_TIME,
        SETTING_RTC_TIME_UP,
        SETTING_RTC_TIME_DOWN,
        SETTING_RTC_TIME_LEFT,
        SETTING_RTC_TIME_RIGHT,
        SETTING_RTC_TIME_OK,
        SETTING_RTC_TIME_DONE,
        SETTING_LIGHT_TIME_CONFIG,
        SETTING_LIGHT_TIME_CONFIG_UP,
        SETTING_LIGHT_TIME_CONFIG_DOWN,
        SETTING_LIGHT_TIME_CONFIG_LEFT,
        SETTING_LIGHT_TIME_CONFIG_RIGHT,
        SETTING_LIGHT_TIME_CONFIG_OK,
        SETTING_LIGHT_TIME_CONFIG_BACK,
        SETTING_LIGHT_TIME_CONFIG_DONE,
        WIFI_PROVISIONING_START,
        WIFI_PROVISIONING_FAILED,
        WIFI_PROVISIONING_DONE,
        SET_WIFI_ERROR,
        SET_FIREBASE_ERROR,
        SET_NTP_ERROR,
        HANDLE_ERROR,
        CHECK_NTP_TIME_UPDATE,
    };

    enum class STATE : uint8_t
    {
        IDLE,
        RUNNING,
        PAUSED,
        WAITING,
        DELAY,
        DONE
    };

    enum class INSERT_LEVEL : uint8_t
    {
        LEVEL0,
        LEVEL1,
        LEVEL2,
        LEVEL3,
        LEVEL4,
        LEVEL5,
        LEVEL6,
        LEVEL7,
        LEVEL8,
        LEVEL9,
        LEVEL10,
        LEVEL11,
        LEVELMAX
    };

    enum class TIMER_SIGNAL : uint8_t
    {
        TIMER_SIGNAL_NONE = 0,
        CONNECT_WIFI_SIGNAL,
        CONNECT_WIFI_DONE,
        CONNECT_FIREBASE_SIGNAL,
        CONNECT_FIREBASE_DONE,
        CONNECT_FIREBASE_GET_TOKEN,
        CONNECT_NTP_SIGNAL,
        CONNECT_NTP_DONE,
        DISPLAY_ALL_TIME_SIGNAL,
        CONNECT_WIFI_FAILED_GOTO_NEXT_MODE,
        CONNECT_FIREBASE_FAILED_GOTO_NEXT_CONNECT,
        CONNECT_NTP_FAILED_GOTO_NEXT_CONNECT,
        SETTING_BUTTON_IR_REMOTE_START,
        SETTING_BUTTON_IR_REMOTE,
        SETTING_BUTTON_IR_REMOTE_DONE,
        SETTING_RTC_TIME_START,
        SETTING_RTC_TIME,
        SETTING_RTC_TIME_DONE,
        SETTING_LIGHT_TIME_CONFIG,
        SETTING_LIGHT_TIME_CONFIG_DONE,
        WIFI_PROVISIONING_START,
        WIFI_PROVISIONING_FAILED,
        TIMER_SIGNAL_MAX
    };

} // namespace utils

#endif // DEFINE_H